# Default values for Pythnet mainnet rpc config 
pythnet:
  logLevel: warn

  expectedBankHash: 84ztrmopeEhQMxweSPvohG3Hv6zgqrvd7pRjR4QQWKoD
  expectedGenesisHash: GLKkBUr6r72nBtGrtBPJLRqtsh8wXZanX4xfnqKnWwKq
  expectedShredVersion: 35891
  entrypoint: entrypoint.pythnet.pyth.network:8001
  messageBufferPid: 7Vbmv1jt4vyuqBZcpYPpnVhrqVe5e6ZPb6JxDcffRHUM
  wormholePid: H3fxXJ86ADW2PNuDDmZJg6mzTtPxkYCpNuQUTgmJ7AjU
  accumulatorSequenceAddr: 8MuVR15V86sSELdpW4UYTyx7WTXRARF1Bj7GJHgTJP3K
  # The values below are for Pythtest
  # expectedBankHash: CjcYdoVMN7i84Fzs1QyyUJbmxaVho5k9MokEjMHtX1xz
  # expectedGenesisHash: EkCkB7RWVrgkcpariRpd3pjf7GwiCMZaMHKUpB5Na1Ve
  # expectedShredVersion: 15535
  # entrypoint: 35.214.10.159:8000
  # messageBufferPid: 7Vbmv1jt4vyuqBZcpYPpnVhrqVe5e6ZPb6JxDcffRHUM
  # wormholePid: EUrRARh92Cdc54xrDn6qzaqjA77NRrCcfbr8kPwoTL4z
  # accumulatorSequenceAddr: Ao4tQp1ouW9w73CE34npzSDjgPG5FGz8KmoSauzCwuh7

# Default values for pythnet-rpc production config
replicaCount: 1

image:
  repository: 192824654885.dkr.ecr.eu-west-2.amazonaws.com/development
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ali-pythnet"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  httpRpcPort: 8899
  wsRpcPort: 8900
  gossipPort: 9999

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits: {}
  requests:
    cpu: 4
    memory: 4Gi

nodeSelector: {}

tolerations: []

affinity: {}
