# Default values for hermes application config. You should replace
# the pythnet endpoint values with your own.
hermes:
  # -- Hermes log level. Valid values are: trace, debug, info, warn, error
  logLevel: warn
  # -- Pythnet Http RPC address. Must be set. Example: http://1.2.3.4:8899
  pythnetHttpAddr:
  # -- Pythnet Websocket RPC address. Must be set. Example: ws://1.2.3.4:8900
  pythnetWsAddr:

  benchmarks:
    # -- Enable benchmarks. Benchmarks endpoint does not support Hermes Beta yet and you need to disable it for that.
    enabled: true
    # -- Benchmarks endpoint.
    endpoint: https://benchmarks.pyth.network

  # -- Whitelisted ip network addresses (in CIDR notation) against websocket ratelimit (separated by comma). Example: 1.2.0.0/24,3.0.0.0/8
  rpcWsWhitelist:

  # -- Wormhole spy rpc address. Must be set. Example: http://1.2.3.4:7072
  wormholeSpyRpcAddr:

  # -- Wormhole contract address
  wormholeContractAddr: H3fxXJ86ADW2PNuDDmZJg6mzTtPxkYCpNuQUTgmJ7AjU

  # The values below are the values for Hermes Beta channel using Wormhole testnet network
  # wormholeContractAddr: EUrRARh92Cdc54xrDn6qzaqjA77NRrCcfbr8kPwoTL4z

# Default values for hermes production config

replicaCount: 2

image:
  repository: public.ecr.aws/pyth-network/hermes
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits: {}
  requests:
    cpu: 2
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
