# Default values for hermes application config. You should replace
# the pythnet endpoint values with your own.
hermes:
  # -- Hermes log level. Valid values are: trace, debug, info, warn, error
  logLevel: warn
  # -- Pythnet Http RPC endpoint. Must be set. Example: http://localhost:8899
  pythnetHttpEndpoint:
  # -- Pythnet Websocket RPC endpoint. Must be set. Example: ws://localhost:8900
  pythnetWsEndpoint:

  # -- Wormhole bootstrap addresses
  whBootstrapAddrs: /dns4/wormhole-mainnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWQp644DK27fd3d4Km3jr7gHiuJJ5ZGmy8hH4py7fP4FP7
  # -- Wormhole network id
  whNetworkId: /wormhole/mainnet/2
  # -- Wormhole contract address
  whContractAddr: H3fxXJ86ADW2PNuDDmZJg6mzTtPxkYCpNuQUTgmJ7AjU

  # The values below are the values for our Hermes Beta using testnet wormhole
  # whBootstrapAddrs: /dns4/wormhole-testnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWAkB9ynDur1Jtoa97LBUp8RXdhzS5uHgAfdTquJbrbN7i
  # whNetworkId: /wormhole/testnet/2/1
  # whContractAddr: EUrRARh92Cdc54xrDn6qzaqjA77NRrCcfbr8kPwoTL4z

# Default values for hermes production config

replicaCount: 1

image:
  repository: public.ecr.aws/pyth-network/hermes
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  runAsNonRoot: true

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits: {}
  requests:
    cpu: 1
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}
